[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['cd backend && npm install --frozen-lockfile']

[phases.build]
cmds = ['cd backend && npm run build']

[start]
cmd = 'cd backend && npm start'